name: Cypress Tests

on:
  push:
    branches:
      - main
      - 'feature/*'
      - 'fix/*'
      - 'hotfix/*'
      - 'release/*'
  pull_request:
    branches:
      - main
      - 'release/*'

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          command: npm test